### ISSUE TITLE
a way to apply rolled dmg to token(s) for condition track movement automation

### ISSUE THREAD

**Issue by ProfBashington** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#302] opened 2022-09-02 01:29 UTC
Maybe a button that appears in the chat box after dmg is rolled applies to all selected, or maybe drag and drop a result out onto the token?

**Comment by ProfBashington** [comment] 2022-09-03 15:52
Might be able to plug this in to do the job:
https://gitlab.com/tposney/midi-qol/

**Comment by ProfBashington** [comment] 2022-09-03 16:08
So I'm understanding now a lot of people don't like everything to be automated to the point where dmg is applied as part of the roll as it happens in midiqol as they will remember things about their roll after the fact, thus making them constantly backtrack and edit things anyways.

Maybe a better template to follow is something like this then?
https://foundryvtt.com/packages/betterrolls5e
https://github.com/RedReign/FoundryVTT-BetterRolls5e

**Comment by kypvalanx** [comment] 2022-09-04 22:44
duplicate of #271

**Comment by kypvalanx** [comment] 2022-09-04 22:45
i've closed it as a duplicate, i will be using this as a reference for the enhancement

**Closed by kypvalanx** 2022-09-04 22:44 UTC

**Comment by kypvalanx** [comment] 2023-01-12 08:05
> So I'm understanding now a lot of people don't like everything to be automated to the point where dmg is applied as part of the roll as it happens in midiqol as they will remember things about their roll after the fact, thus making them constantly backtrack and edit things anyways.

this can be based on a system option
