### ISSUE TITLE
"Abilities" table on Summary tab of character sheet doesn't update when species is deleted or changed.

### ISSUE THREAD

**Issue by jasony1974** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#1] opened 2021-04-19 11:08 UTC
The "Abilities" table doesn't update when a species is deleted or changed.

**Comment by kypvalanx** [comment] 2021-04-19 19:51
i currently cannot replicate, can you provide more details?  i can add the Aqualish species and remove it and it appears to work.

**Comment by jasony1974** [comment] 2021-04-19 20:15
Yes, let me know what info you need, and I'll try my best to get you
what you need.  I'm on Windows 10 & Foundry 0.7.9

I just tried it with Aqualish, as follows:

   - Create Actor>Create New Actor.  [image: image.png]
   - Then on the Summary tab, click on the folder icon at the end of the
   "Add Species" field.  Then select and drag Aqualish to the
character sheet. [image:
   image.png]
   - The "Abilities" table populates, but the Species field itself does
   not.  [image: image.png]
   - I then click on the trash can icon, which brings up the
   delete confirmation dialog.[image: image.png]
   - I click "Yes", and the dialog box closes, the icon for species goes
   away, the "Add SPecies" placeholder text reappears, as does the folder
   icon, but the Abilites table remains populated with Aqualish traits.[image:
   image.png]

**Comment by jasony1974** [comment] 2021-04-19 20:20
Also, on this issue, if I hover over the "add Species" placeholder test, it
appears as a hyperlink, which implies that it would open the Species list
from the compendium, but nothing happens if I click the text.

**Comment by kypvalanx** [comment] 2021-04-19 20:27
> Also, on this issue, if I hover over the "add Species" placeholder test, it appears as a hyperlink, which implies that it would open the Species list from the compendium, but nothing happens if I click the text.


this is technically working as intended, but only because i added the text later and didn't think about how terrible that is.

**Comment by jasony1974** [comment] 2021-04-19 20:30
Ok, that’s fine. I was just trying to see if I could solve my own problem
but taking a different approach. And wanted to give you that extra info, in
case it revealed a clue.

**Comment by kypvalanx** [comment] 2021-04-19 20:31
you pointed out bad design that i will be fixing, but alas, that doesn't help with the current issue.  is foundry being run on a local instance?  via browser?  both of your issues seem like something isn't refreshing correctly.

**Comment by jasony1974** [comment] 2021-04-19 20:36
I am running Foundry on a local instance

**Comment by kypvalanx** [comment] 2021-04-19 20:37
what version?

**Comment by jasony1974** [comment] 2021-04-19 20:38
0.7.9

**Comment by jasony1974** [comment] 2021-04-19 20:54
I wondering about refresh issues, so I have been hitting F5 to force the app to  refresh, then reopening the character sheet, but it is still the same behavior.

Is there some way that maybe something didn't completely install?  This is what I see on the Attributes tab of a Species...

![Screenshot 2021-04-19 165317](https://user-images.githubusercontent.com/79643334/115301978-e86e2700-a12f-11eb-9958-003cfb346f51.png)

**Comment by kypvalanx** [comment] 2021-04-19 21:34
the attributes tab isn't really done at the moment.  for some item types it will display correctly and for others, it won't.

**Comment by jasony1974** [comment] 2021-04-19 21:38
ok, was hoping that might shed some light.

I uninstalled the system, and re-installed.  The Console log seems to show everything that' supposed to happen during the generation routine, so I think everything is installing correctly.

Probably unrelated, but the hyperlinks in the various species cards just point to the root...

**Comment by kypvalanx** [comment] 2021-04-19 21:39
that's a data generation bug, if you could log it, i'll get to it.

**Comment by kypvalanx** [comment] 2021-04-26 13:06
this should be fixed by 0.2.1

**Closed** 2021-04-29 14:16 UTC
Labels: bug
