### ISSUE TITLE
[Bug] Prestige Classes Talent Prerequisites

### ISSUE THREAD

**Issue by LeKopic** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#171] opened 2022-04-27 11:28 UTC
It appears there are a few issues with PC prereqs:
1) Pathfinder require one talent from Awareness Talent Tree instead of at least two Talents from the Awareness Talent Tree, Camouflage Talent Tree, or Survivor Talent Tree
2) Force Adept - has a prerequisite of one "Force Talent", but the system has only "Force Talent Trees". And even then, Force Adept requires at least three of them.
3) Bounty Hunter - requires only one Awareness Talent
4) Force Disciple requires one Dark Side Devotee talent
5) Infiltrator - works ok, except for missing prereq warning:
![image](https://user-images.githubusercontent.com/42682507/165507704-52334c0c-cbf2-48ea-8dd3-003e7fc2b4b6.png)
If you have selected a talent from either tree - the warning will say that you must take a talent from another tree, which is not correct as you can take a talent from the same tree.
6) Master Privateer - requires one talent from Misfortune Talent Tree as opposed to at least two Talents from either the Misfortune Talent Tree, the Smuggling Talent Tree, or the Spacer Talent Tree

The most curious thing is that Infiltrator works almost as intended, while having the same "at least 2 talents".

**Comment by kypvalanx** [comment] 2022-05-14 11:11
1. the parser that should have handled Pathfinder's talent requirement didn't allow for "," and so would only find the first tree

**Comment by kypvalanx** [comment] 2022-05-14 11:14
2. prerequisite generation for force adept was being hard coded

**Comment by kypvalanx** [comment] 2022-05-14 11:20
3. when only one option for tree type was available it was defaulting to one choice for bounty hunter

**Comment by kypvalanx** [comment] 2022-05-14 11:22
4. same as pathfinder

**Comment by kypvalanx** [comment] 2022-05-14 11:27
5. the data for this one is correct, there must be a prerequisite problem in the js
6. same as pathfinder.

most of this was caused by a comma

**Comment by kypvalanx** [comment] 2022-05-14 13:40
fixed in 0.5.18

**Closed by kypvalanx** 2022-05-14 13:40 UTC
Labels: bug
