### ISSUE TITLE
[Bug][0.5.3][V9] HP doesn't count CON mod

### ISSUE THREAD

**Issue by sanpats** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#155] opened 2022-03-27 11:30 UTC
Previous version doesn't have this bug, but now HP won't include CON mods.
![image](https://user-images.githubusercontent.com/22677493/160279409-12ea637b-69a0-4ca2-be5d-dc3e11c0783d.png)

**Comment by TalonKetupa** [comment] 2022-03-27 13:16
Related note: calculation for fortitude defense is also broken now. It uses strength modifier instead of constitution.

**Comment by LeKopic** [comment] 2022-04-01 18:30
I'm certain that the issue is in the lines 33 to 37 of Health.Js, in resolveAttributeMod function. It works if the line 34 is "if(ignoreCon == 0)" instead of "if(IgnoreCon)".

**Comment by LeKopic** [comment] 2022-04-01 18:59
Or, rather, the issue is in IgnoreCon itself, considering that it works if it is = 0. True/false mix-up? My quite basic ability to read code is not enough

**Comment by Orkah** [comment] 2022-04-01 20:29
I am not sure of why this is a problem as of this version, but it can simply be fixed at line 993 of module/actor/actor.js.

    ignoreCon() {
        return this.data.data.attributes.con?.skip || true;
    }

this.data.data.attributes.con.skip is already set to a boolean value.
If it's not false, then it's gonna be true. Therefore, we would not need the "|| true" statement at the end.

    ignoreCon() {
        return this.data.data.attributes.con?.skip;
    }

Or maybe I am missing something?

**Comment by Orkah** [comment] 2022-04-01 20:34
Both problem are related as described by TalonKetupa. It is fixed on my side now.

/module/actor/defense.js line 249

function _getFortStatMod(actor) {
    let attributes = actor.data.data.attributes;
    return actor.ignoreCon() ? attributes.str.mod : attributes.con.mod;
}

**Comment by kypvalanx** [comment] 2022-05-04 12:53
what CON mod should be applied?  i see a +2 coming from CON per level in the "Attribute Bonus HP" column

**Comment by kypvalanx** [comment] 2022-05-04 12:55
the or true was added because vehicles don't hve a CON mod and therefore this method would return "undefined" instead of false and that's a problem.  it should likely be defaulted to false though

**Closed** 2022-05-04 13:09 UTC
