### ISSUE TITLE
[Bug] Force Talent Tree prerequisite 

### ISSUE THREAD

**Issue by LeKopic** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#159] opened 2022-04-01 21:55 UTC
It appears that Force Sensitivity Feat provides bonusTalentTree attribute "Force Talent Tree", but all Force Talents (at least I think all?) require "Force Talent Tree**s**" attribute

**Comment by Orkah** [comment] 2022-04-01 22:26
I am not sure I follow you, but I've noticed that you cannot take "Force Recovery" as a Jedi 1, because it doesn't have the 
"Jedi Talent Trees" categories. It only have the "Talent Trees, Force Talent Trees" categories.

Therefore, acquiring the Force Sensitivity feat should add the attribute "Force Talent Trees" as well, in order to pick up those related talents.

Do I follow you correctly?

**Comment by LeKopic** [comment] 2022-04-01 22:32
Yeah, that's correct
![image](https://user-images.githubusercontent.com/42682507/161350340-663db4db-9242-4a21-9b1e-ff7eda26ff49.png)
The easy fix is to change bonusTalentTree "Force Talent Tree" to Force Talent Trees, but I haven't checked whether all Force Talents use Trees instead of Tree.

**Comment by Orkah** [comment] 2022-04-01 22:46
You nailed it, I've changed the attribute from swse-feats.db and added the S in Trees.
When trying to add Force Recovery, it asked me for Equilibrium, as intended.

**Comment by Orkah** [comment] 2022-04-01 23:09
I've commited the fixes on my fork, friend ;)

**Comment by LilLiteralist** [comment] 2022-04-26 19:56
Wow, I never would have figured this out myself. Good catch!

**Comment by kypvalanx** [comment] 2022-05-13 22:54
force talents should all use the same tree.  i'll double check before pushing an update

**Comment by kypvalanx** [comment] 2022-05-13 23:01
https://github.com/kypvalanx/Foundry-VTT-StarWars-SagaEdition/commit/b488097cf4e5e95f5a5dcc20b708647551844598

**Comment by kypvalanx** [comment] 2022-05-14 02:30
it's fixed in 0.5.17

**Closed by kypvalanx** 2022-05-14 02:30 UTC
