### ISSUE TITLE
Yuuzhan Vong Advanced Agent Damage Threshold miscalculated

### ISSUE THREAD

**Issue by cpadilla** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#430] opened 2023-09-30 23:20 UTC
There seems to be a bug with a nonheroic character I created. It says the Damage Threshold is 898, which is absurdly high.

I copied most of the stats from the Yuuzhan Vong Advanced Agent (CL 4) npc in the Compendium, which had a lot of validation errors (another issue) so this character was my attempt to fix them.

I've attached the character in json format. I changed the extension to .txt.

![image](https://github.com/kypvalanx/Foundry-VTT-StarWars-SagaEdition/assets/1704172/961944b5-9064-4711-adbb-9f552d21760d)

[yuuzhan vong agent.txt](https://github.com/kypvalanx/Foundry-VTT-StarWars-SagaEdition/files/12775686/yuuzhan.vong.agent.txt)

**Comment by cpadilla** [comment] 2023-10-01 21:34
I also just noticed the Reflex Defense looks wrong. It seems like it's getting -30 from the Medium trait.

![image](https://github.com/kypvalanx/Foundry-VTT-StarWars-SagaEdition/assets/1704172/c883ea71-5833-4b7e-bd0d-bae2f98779eb)

**Comment by kypvalanx** [comment] 2023-11-22 16:35
the problem is that when "ignore prerequisites" is selected, it ignores prerequisites on character build as well as when adding a new item.  if you turn off "ignore prerequisites" your sheet is correct.  i do need to fix that though because that's not intended.

**Comment by kypvalanx** [comment] 2024-03-29 02:05
fixed in 06490fe516548f3d20d4bf18a4c09886ac59b2a5

**Closed by kypvalanx** 2024-03-29 02:05 UTC
Labels: bug
