### ISSUE TITLE
[Bug][V9] Weapon Finesse feat doesn't work.

### ISSUE THREAD

**Issue by sanpats** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#133] opened 2022-02-05 21:16 UTC
Weapon Finesse feat should make melee attacks use DEX or STR, whatever is higher.

**Comment by kypvalanx** [comment] 2022-02-06 15:21
I can't reproduce this issue, it appears to work.  make sure that the weapon is light, a lightsaber, or a one handed weapon with weapon focus

**Comment by sanpats** [comment] 2022-02-08 12:29
![image](https://user-images.githubusercontent.com/22677493/152986976-6a15c0bb-db08-4866-b51f-a699e5505aea.png)
![image](https://user-images.githubusercontent.com/22677493/152987050-f9b47069-5e40-4f02-8cfd-c675aa6158cb.png)
![image](https://user-images.githubusercontent.com/22677493/152987084-4021e795-958e-4176-b1ff-c2d15b4fa12c.png)
![image](https://user-images.githubusercontent.com/22677493/152987120-615ebc12-7e1c-41fd-8046-e2c13f3283e3.png)
Only a lightsaber is equiped. Still use STR mod for attack (BA 2 + STR Mod -1 = 1)

**Comment by sanpats** [comment] 2022-02-08 12:38
It appears that Weapon Finesse feat works with unarmed attack but not lightsaber.

**Comment by kypvalanx** [comment] 2022-03-13 19:18
found the issue, fix will be released soon

**Comment by kypvalanx** [comment] 2022-03-13 21:09
[fixed with ](https://github.com/kypvalanx/Foundry-VTT-StarWars-SagaEdition/tree/0.5.3)

**Comment by kypvalanx** [comment] 2022-03-13 21:09
fixed with [0.5.3](https://github.com/kypvalanx/Foundry-VTT-StarWars-SagaEdition/tree/0.5.3)

**Closed by kypvalanx** 2022-03-13 21:09 UTC
